#!/usr/bin/env bash

set -e

BLUE='\033[0;34m'
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# arg="${1:?[error]: ArgumentRequired. [up/down]}"
arg=${1:-}

source scripts/lib/load-env

envload

DB_SERVICE="${DOCKER_DB_SERVICE}"
APP_SERVICE="${DOCKER_APP_SERVICE}"
PG_DB="${DB_NAME}"
PG_HOST="${DB_HOST}"
PG_USER="${DB_USER}"
PG_PASSWORD="${DB_PASSWORD}"


arg-logic() {
    if [[ "$arg" != "up" && "$arg" != "down" ]]; then
        echo -e "${RED}[error]:\tInvalidArgument \tLiteral[up, down]${NC}" >&2
        exit 1

    elif [[ "$arg" == "up" ]]; then
        cd "docker"
        docker compose --env-file ../.env up -d
        # proper health check loop:
        until docker exec $DB_SERVICE pg_isready -U $PG_USER -h $PG_HOST >/dev/null 2>&1; do
            echo -e "${BLUE}[debug]: \t__waiting_for_db__${NC}" >&2
            sleep 1
        done
        echo -e "${GREEN}[info]: \t__network_up__${NC}"

    else
        cd "docker"
        docker compose --env-file ../.env down
        echo -e "${GREEN}[info]: \t__network_down__${NC}"
    fi
}

if ! (return 2>/dev/null); then
    arg-logic
fi
